name: "Upload asset to Github release"
description: "Uploads an asset to a Github release. Use on release trigger."
branding:
  icon: box
  color: blue
author: "Asplan Viak"
inputs:
  file:
    description: "File name"
    required: true
runs:
  using: "node16"
  main: "dist/index.js"
